<script>
  let count = 0
</script>

<div class="title-page">
  <h1>
    <span class="first-row">Hello,</span>
    <br />
    <span class="second-row">
      my name is
      <span class="text-gradient">Aleksi Koivu</span>
    </span>
  </h1>
  <a class="down-arrow fade-in-bottom" href="#about">
    <img src="/images/up-arrow.png" alt="An arrow pointing down." />
  </a>
</div>

<style lang="scss">
  @import "../styles/index.scss";
  .title-page {
    position: relative;
    margin-top: -74px;
    display: flex;
    height: calc(100vh);
    gap: 2rem;
    align-items: center;
    justify-content: center;
  }
  h1 {
    font-size: 3rem;
    font-family: "Unbounded", Roboto, Arial;
    font-weight: 300;
    background: -webkit-linear-gradient(white, #38495a);
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-weight: 800;
    margin: 0;
  }

  .first-row {
    animation: fadeIn 1.5s;
  }
  .second-row {
    animation: fadeInTwo 1.5s;
  }

  .down-arrow {
    position: absolute;
    bottom: 5%;
    rotate: 180deg;
    transition: 0.2s all ease;
    &:hover {
      scale: 1.1;
      cursor: pointer;
    }
  }
  .fade-in-bottom {
    -webkit-animation: fade-in-bottom 0.7s cubic-bezier(0.39, 0.575, 0.565, 1)
      both;
    animation: fade-in-bottom 0.7s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation-delay: 1s;
    -webkit-animation-delay: 1s;
  }
  @keyframes fadeIn {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fadeInTwo {
    0% {
      opacity: 0;
    }
    50% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-7-16 13:40:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-in-bottom
 * ----------------------------------------
 */
  @-webkit-keyframes fade-in-bottom {
    0% {
      -webkit-transform: translateY(50px);
      transform: translateY(50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes fade-in-bottom {
    0% {
      -webkit-transform: translateY(50px);
      transform: translateY(50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
</style>
